language: haskell
ghc: 7.8
script:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - cabal test
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=test --exclude-dir=benchmark timsort-tests
